site_name: nixos-facter
theme:
  name: material
  features:
    - navigation.sections
    - search.suggest
  palette:
    primary: white
    accent: deep_orange

nav:
  - Explanation:
      - Placeholder: ""
  - Tutorial:
      - Placeholder: ""
  - How-to:
      - Placeholder: ""
  - Reference:
      - Placeholder: ""

plugins:
  - search
  - mermaid2:
      # resolve js dependency locally rather than at runtime
      javascript: ./js/mermaid/mermaid.esm.min.mjs
